config/routes.rb
Q2Flash::Application.routes.draw do
  devise_for :users

  namespace :admin do
    resources :users
    resources :black_domains, :except => [:show, :update]
    resources :brochures do
      resources :pdfs
    end
    match 'settings' => 'settings#edit', :as => :edit_settings
    match 'settings/update' => 'settings#update', :as => :update_settings
    root :to => 'home#index'
  end

  match 'flash_page/show' => 'flash_page#show', :as => :flash_game
  root :to => "flash_page#show"
end

app/models/black_domain.rb
class BlackDomain < ActiveRecord::Base
  validates_uniqueness_of :domain_name
  validates_format_of :domain_name, :with => /^([a-zA-Z0-9]([a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])?\.)+[a-zA-Z]{2,6}$/
  validates_presence_of :domain_name
end

app/models/brochure.rb
class Brochure < ActiveRecord::Base
  has_many :pdfs
end

app/models/pdf.rb
class Pdf < ActiveRecord::Base
  belongs_to :brochure
  has_attached_file :attachment
  
  def url
    attachment.url
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validate :check_domain_name
  before_validation :generate_password!
  after_create :send_confirmation
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, 
    :first_name, :last_name, :title, :financial_institution, :phone, :role

  def role?(role)
    self.role == role
  end

  def full_name
    [first_name, last_name].join(' ')
  end

  def generate_password!
    user_password = SexyTempPassword.generate
    self.password = user_password
    self.password_confirmation = user_password
  end

  def send_confirmation
    UserMailer.registration_confirmation(self, self.password).deliver
  end
  
  private

  def check_domain_name
    domain_names = BlackDomain.all.map(&:domain_name)
    email_domain = email.split('@').last

    result = domain_names.detect do |domain_name|
      email_domain =~ Regexp.new("^#{domain_name}$")
    end
    self.errors.add(:email, "not allowed domain name") if result
  end
end

app/controllers/admin/black_domains_controller.rb
class Admin::BlackDomainsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :admin_required

  def index
    @black_domains = BlackDomain.all
  end

  def create
    @black_domain = BlackDomain.new(params[:black_domain])

    respond_to do |format|
      if @black_domain.save
        format.html { redirect_to(admin_black_domains_path, :notice => 'Author was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def new
    @black_domain = BlackDomain.new
  end

  def destroy
    @black_domain = BlackDomain.find(params[:id])
    @black_domain.destroy
    redirect_to :admin_black_domains
  end
end

app/controllers/admin/brochures_controller.rb
class Admin::BrochuresController < ApplicationController
  before_filter :authenticate_user!
  inherit_resources
  def index
    @brochures = Brochure.all
    respond_to do |format|
      format.html
      format.xml do 
        render :xml => @brochures.to_xml(
          :include => {
            :pdfs => {:methods => :url}
          },
          :only => [:name, :description, :created_at, :updated_at]
        )
      end
    end
  end
end

app/controllers/admin/pdfs_controller.rb
class Admin::PdfsController < ApplicationController
  before_filter :authenticate_user!
  inherit_resources
  belongs_to :brochure
end

app/controllers/admin/settings_controller.rb
class Admin::SettingsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :admin_required

  def edit
  end

  def update
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :admin_required
  
  def index
    @users = User.all
  end
  
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def admin_required
    if !user_signed_in? || !current_user.role?('admin')
      redirect_to(new_user_session_path)
    end
  end
end

app/controllers/flash_page_controller.rb
class FlashPageController < ApplicationController
  before_filter :authenticate_user!

  def show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!

  def index
  end
end

app/helpers/admin/black_domains_helper.rb
module Admin::BlackDomainsHelper
end

app/helpers/admin/settings_helper.rb
module Admin::SettingsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brochures_helper.rb
module BrochuresHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/flash_page_helper.rb
module FlashPageHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/pdfs_helper.rb
module PdfsHelper
end

app/views/admin/black_domains/_form.html.erb
</br>
<p>
<% form_for [:admin, @black_domain] do |f| -%>
  <%= f.label :domain_name, 'Domain name' %></br>
  <%= f.text_field :domain_name%></br>
  <%= f.submit "submit" %>
<% end -%>
</p>

app/views/admin/black_domains/index.html.erb
<br/>
<% @black_domains.each_with_index do |black_domain, i| %>
  <p>
    <%= i + 1 %>. <%= black_domain.domain_name %>
    <%= link_to "Delete", admin_black_domain_path(black_domain), :method => :delete, :confirm => 'Are you sure?'  %>
  </p>
<% end %>

<p><%= link_to "Create", new_admin_black_domain_path %></p>

app/views/admin/black_domains/new.html.erb
<%= error_messages_for @black_domain %>
<%= render 'form', :locals => {:black_domain => @black_domain} %>

app/views/admin/brochures/edit.html.haml
= form_for @brochure, :url => admin_brochure_path(@brochure) do |form|
  %p
    = form.label :name
    = form.text_field :name
  %p
    = form.label :description
    = form.text_area :description
  %p
    = form.submit 'Update'

app/views/admin/brochures/index.html.haml
- title 'Brochures'
%table#brochures
  - @brochures.each do |brochure|
    %tr
      %td.name
        = link_to brochure.name, admin_brochure_path(brochure)
      %td.controls
        = link_to 'edit', edit_admin_brochure_path(brochure)
        = link_to 'delete', admin_brochure_path(brochure), :method => :delete,
          :confirm => 'Are you sure?'

= link_to 'add new brochure', new_admin_brochure_path, :class => :button

app/views/admin/brochures/new.html.haml
= form_for @brochure, :url => admin_brochures_path do |form|
  %p
    = form.label :name
    = form.text_field :name
  %p
    = form.label :description
    = form.text_area :description
  %p
    = form.submit 'Create'

app/views/admin/brochures/show.html.haml
- title @brochure.name
%p
  = @brochure.description
%table#brochures
  - @brochure.pdfs.each do |pdf|
    %tr
      %td.name
        = pdf.name
      %td.controls
        = link_to 'edit', edit_admin_brochure_pdf_path(@brochure, pdf)
        = link_to 'delete', admin_brochure_pdf_path(@brochure, pdf), :method => :delete,
          :confirm => 'Are you sure?'

= link_to 'add new pdf', new_admin_brochure_pdf_path(@brochure), :class => :button

app/views/admin/pdfs/_form.html.haml
%p
  = form.label :brochure
  = form.select :brochure_id, Brochure.all.map{|b| [b.name, b.id]}
%p
  = form.label :name
  = form.text_field :name
%p
  = form.label :attachment
  = form.file_field :attachment
%p
  = form.label :description
  = form.text_area :description

app/views/admin/pdfs/edit.html.haml
= error_messages_for @pdf
= form_for @pdf, :url => admin_brochure_pdf_path(@brochure, @pdf),
  :html => {:multipart => true} do |form|
  = render 'form', :form => form
  %p
    = form.submit 'Update'

app/views/admin/pdfs/new.html.haml
= error_messages_for @pdf
= form_for @pdf, :url => admin_brochure_pdfs_path(@brochure),
  :html => {:multipart => true} do |form|
  = render 'form', :form => form
  %p
    = form.submit 'Create'

app/views/admin/pdfs/show.html.haml
- title @pdf.name
%p
  = @pdf.description
- if @pdf.attachment.exists?
  = link_to 'Attachemnt', @pdf.attachment.url

app/views/admin/users/edit.html.haml
- title 'Edit user'
= form_for @user, :url => admin_user_path(@user) do |form|
  %p
    = form.label :email
    = form.text_field :email
  %p
    = form.label :password
    = form.text_field :password
  %p
    = form.label :password_confirmation
    = form.text_field :password_confirmation
  %p
    = form.submit 'Update'

app/views/admin/users/index.html.haml
- title 'Users'
%table#users
  - @users.each do |user|
    %tr
      %td.name
        = user.email
      %td.controls
        = link_to 'edit', edit_admin_user_path(user)
        = link_to 'delete', admin_user_path(user), :method => :delete,
          :confirm => 'Are you sure?'

app/views/flash_page/show.html.erb
<h1>Flash game</h1>

app/views/home/index.html.haml
%h2
  Flash application